name: Deploy K8s API Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy k8s‑api‑infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: k8s-api-infrastructure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Terraform Init
        run: terraform init

      - name: Apply core infra modules
        run: |
          terraform apply -auto-approve \
            -target=module.iam \
            -target=module.vpc \
            -target=module.eks_cluster \
            -target=module.eks_managed_nodes \
            -target=module.security_groups

      - name: Apply Ingress‑NGINX Helm release
        run: terraform apply -auto-approve -target=helm_release.ingress_nginx

      - name: Apply CloudFront & Route53
        run: |
          terraform apply -auto-approve \
            -target=module.cloudfront \
            -target=module.route53_api_record
