name: Deploy K8s API Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy k8s‑api‑infrastructure
    runs-on: ubuntu-latest
    env:
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_environment: ${{ secrets.TF_VAR_ENVIRONMENT }}
      TF_VAR_project_name: ${{ secrets.TF_VAR_PROJECT_NAME }}
      TF_VAR_backend_bucket: ${{ secrets.TF_VAR_BACKEND_BUCKET }}
      TF_VAR_backend_bucket_key: ${{ secrets.TF_VAR_BACKEND_BUCKET_KEY }}
      TF_VAR_dynamodb_table: ${{ secrets.TF_VAR_DYNAMODB_TABLE }}
      TF_VAR_cluster_name: ${{ secrets.TF_VAR_CLUSTER_NAME }}
      TF_VAR_node_group_name: ${{ secrets.TF_VAR_NODE_GROUP_NAME }}
      TF_VAR_repo_name: ${{ secrets.TF_VAR_REPO_NAME }}
      TF_VAR_ec2_ssh_key: ${{ secrets.TF_VAR_EC2_SSH_KEY}}
      TF_VAR_vpc_cidr: ${{ secrets.TF_VAR_VPC_CIDR }}
      TF_VAR_availability_zones: ${{ secrets.TF_VAR_AVAILABILITY_ZONE }}
      TF_VAR_aliases: ${{ secrets.TF_VAR_ALIASES }}
      TF_VAR_zone_name: ${{ secrets.TF_VAR_ZONE_NAME }}
      TF_VAR_zone_comment: ${{ secrets.TF_VAR_ZONE_COMMENT }}
      TF_VAR_domain_name: ${{ secrets.TF_VAR_DOMAIN_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_VAR_backend_bucket }}" \
            -backend-config="key=${{ secrets.TF_VAR_backend_bucket_key }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_VAR_dynamodb_table }}"

      - name: Apply core infra modules
        run: |
          terraform apply -auto-approve \
            -target=module.iam \
            -target=module.vpc \
            -target=module.eks_cluster \
            -target=module.eks_managed_nodes \
            -target=module.security_groups

      - name: Apply Ingress‑NGINX Helm release
        run: terraform apply -auto-approve -target=helm_release.ingress_nginx

      - name: Apply CloudFront & Route53
        run: |
          terraform apply -auto-approve \
            -target=module.cloudfront \
            -target=module.route53_api_record